CREATE SCHEMA BANK;

CREATE TABLE BANK.ACCOUNT( ACCOUNT_NUMBER BIGINT NOT NULL PRIMARY KEY,
	PIN INT NOT NULL, 
	OPENING_BALANCE DOUBLE NOT NULL,
	OVERDRAFT DOUBLE NOT NULL
	);
	
CREATE TABLE BANK.TRANSACTION_DETAILS( ACCOUNT_NUMBER BIGINT NOT NULL,
	TRANSACTION_TIME TIMESTAMP NOT NULL,
	TRANSACTION_AMOUNT DOUBLE NOT NULL,
	CONSTRAINT PEOPLE_PK PRIMARY KEY (ACCOUNT_NUMBER, TRANSACTION_TIME)
	);
	
CREATE TABLE BANK.ATM_BALANCE( ATM_AMOUNT DOUBLE NOT NULL
	);